import argparse
import os

import matplotlib.pyplot as plt
import pandas as pd


def parse_args():
    parser = argparse.ArgumentParser(description="Generate timing analysis plots from summary.csv")
    parser.add_argument(
        "--summary",
        type=str,
        required=True,
        help="Path to summary.csv generated by run_batch.py",
    )
    parser.add_argument(
        "--out_dir",
        type=str,
        default=None,
        help="Directory for output plots (defaults to summary parent dir)",
    )
    return parser.parse_args()


def save_histogram(series, title, xlabel, out_path, bins=20):
    plt.figure(figsize=(9, 5))
    plt.hist(series, bins=min(bins, max(3, len(series))), edgecolor="black", alpha=0.85)
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel("Count")
    plt.grid(alpha=0.2)
    plt.tight_layout()
    plt.savefig(out_path, dpi=160)
    plt.close()


def save_scatter(x, y, title, xlabel, ylabel, out_path):
    plt.figure(figsize=(8, 5))
    plt.scatter(x, y, alpha=0.8)
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.grid(alpha=0.2)
    plt.tight_layout()
    plt.savefig(out_path, dpi=160)
    plt.close()


def save_boxplot(df, out_path):
    plt.figure(figsize=(8, 5))
    plt.boxplot([df["total_time_s"], df["avg_token_time_s"]], labels=["total_time_s", "avg_token_time_s"])
    plt.title("Timing distribution (boxplot)")
    plt.ylabel("Seconds")
    plt.grid(alpha=0.2, axis="y")
    plt.tight_layout()
    plt.savefig(out_path, dpi=160)
    plt.close()


def save_sorted_bar(df, out_path):
    plot_df = df.sort_values("total_time_s").reset_index(drop=True)
    plt.figure(figsize=(11, 5))
    plt.bar(plot_df["id"], plot_df["total_time_s"], alpha=0.9)
    plt.xticks(rotation=90)
    plt.title("Prompt total time per sample (sorted)")
    plt.xlabel("Sample id")
    plt.ylabel("total_time_s")
    plt.grid(alpha=0.2, axis="y")
    plt.tight_layout()
    plt.savefig(out_path, dpi=160)
    plt.close()


def main():
    args = parse_args()

    if not os.path.exists(args.summary):
        raise FileNotFoundError(f"summary.csv not found: {args.summary}")

    df = pd.read_csv(args.summary)
    required_cols = {"id", "similarity", "total_time_s", "avg_token_time_s", "num_tokens"}
    missing = required_cols.difference(df.columns)
    if missing:
        raise ValueError(f"Missing required columns in summary.csv: {sorted(missing)}")

    out_dir = args.out_dir or os.path.dirname(args.summary)
    os.makedirs(out_dir, exist_ok=True)

    # Basic statistics
    prompt_stats = df["total_time_s"].describe()
    token_stats = df["avg_token_time_s"].describe()
    corr_prompt_similarity = df["total_time_s"].corr(df["similarity"])
    corr_token_similarity = df["avg_token_time_s"].corr(df["similarity"])

    stats_path = os.path.join(out_dir, "timing_stats.txt")
    with open(stats_path, "w", encoding="utf-8") as f:
        f.write("=== Prompt time stats (s) ===\n")
        f.write(prompt_stats.to_string())
        f.write("\n\n=== Avg token time stats (s) ===\n")
        f.write(token_stats.to_string())
        f.write("\n\n=== Correlations ===\n")
        f.write(f"corr(total_time_s, similarity): {corr_prompt_similarity}\n")
        f.write(f"corr(avg_token_time_s, similarity): {corr_token_similarity}\n")

    save_histogram(
        df["total_time_s"],
        "Distribution of total prompt inversion time",
        "total_time_s",
        os.path.join(out_dir, "hist_total_time_s.png"),
    )
    save_histogram(
        df["avg_token_time_s"],
        "Distribution of average token inversion time",
        "avg_token_time_s",
        os.path.join(out_dir, "hist_avg_token_time_s.png"),
    )
    save_boxplot(df, os.path.join(out_dir, "boxplot_timing.png"))
    save_sorted_bar(df, os.path.join(out_dir, "bar_total_time_sorted.png"))
    save_scatter(
        df["total_time_s"],
        df["similarity"],
        "Prompt time vs reconstruction similarity",
        "total_time_s",
        "similarity",
        os.path.join(out_dir, "scatter_total_time_vs_similarity.png"),
    )
    save_scatter(
        df["avg_token_time_s"],
        df["similarity"],
        "Avg token time vs reconstruction similarity",
        "avg_token_time_s",
        "similarity",
        os.path.join(out_dir, "scatter_avg_token_time_vs_similarity.png"),
    )

    print(f"Saved plots and stats to: {out_dir}")
    print(f"Samples analyzed: {len(df)}")


if __name__ == "__main__":
    main()
